language: go
go_import_path: github.com/ManageIQ-Exchange/manageiq-exchange-cli-go
go:
    - 1.8.x
    - 1.9.x
    - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
sudo: false
install:
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
    - go get golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls
script:
    - export PATH=$PATH:$HOME/gopath/bin
    - export GORACE="halt_on_error=1"
    - test -z "$(gometalinter --disable-all
      --enable=gofmt
      --enable=golint
      --enable=vet
      --enable=gosimple
      --enable=unconvert
      --deadline=4m ./spew | tee /dev/stderr)"
    - make test
    - make CI-Coverage
