language: go
go_import_path: github.com/ManageIQ-Exchange/manageiq-exchange-cli-go
go:
    - 1.8.x
    - 1.9.x
    - tip
sudo: false
install:
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
script:
    - export PATH=$PATH:$HOME/gopath/bin
    - export GORACE="halt_on_error=1"
    - test -z "$(gometalinter --disable-all
      --enable=gofmt
      --enable=golint
      --enable=vet
      --enable=gosimple
      --enable=unconvert
      --deadline=4m ./spew | tee /dev/stderr)"
    - go test -v -race -tags safe ./manageiq-exchange
    - go test -v -race -tags testcgo ./manageiq-exchange -covermode=atomic -coverprofile=profile.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=profile.cov -service=travis-ci
